{
  "name": "SemanticModel",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "name": "SqlServer DESKTOP-M17BHFKMSSQLSERVER19 WideWorldImportersDW",
        "connectionString": "Provider=SQLNCLI11;Data Source=DESKTOP-M17BHFK\\MSSQLSERVER19;Initial Catalog=WideWorldImportersDW;Integrated Security=SSPI;Persist Security Info=false",
        "impersonationMode": "impersonateAccount",
        "account": "stefan",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "City",
        "columns": [
          {
            "name": "City Key",
            "dataType": "int64",
            "sourceColumn": "City Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "WWI City ID",
            "dataType": "int64",
            "sourceColumn": "WWI City ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "sourceProviderType": "WChar"
          },
          {
            "name": "State Province",
            "dataType": "string",
            "sourceColumn": "State Province",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "Sales Territory",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Subregion",
            "dataType": "string",
            "sourceColumn": "Subregion",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location",
            "sourceProviderType": "132"
          },
          {
            "name": "Latest Recorded Population",
            "dataType": "int64",
            "sourceColumn": "Latest Recorded Population",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "City",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[City].* FROM [Dimension].[City] ",
              "dataSource": "SqlServer DESKTOP-M17BHFKMSSQLSERVER19 WideWorldImportersDW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[City].* FROM [Dimension].[City] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "City"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "int64",
            "sourceColumn": "Customer Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "WWI Customer ID",
            "dataType": "int64",
            "sourceColumn": "WWI Customer ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "Customer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Bill To Customer",
            "dataType": "string",
            "sourceColumn": "Bill To Customer",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Buying Group",
            "dataType": "string",
            "sourceColumn": "Buying Group",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Primary Contact",
            "dataType": "string",
            "sourceColumn": "Primary Contact",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Postal Code",
            "dataType": "string",
            "sourceColumn": "Postal Code",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Customer",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Customer].* FROM [Dimension].[Customer] ",
              "dataSource": "SqlServer DESKTOP-M17BHFKMSSQLSERVER19 WideWorldImportersDW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Customer].* FROM [Dimension].[Customer] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Customer"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Employee",
        "columns": [
          {
            "name": "Employee Key",
            "dataType": "int64",
            "sourceColumn": "Employee Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "WWI Employee ID",
            "dataType": "int64",
            "sourceColumn": "WWI Employee ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Employee",
            "dataType": "string",
            "sourceColumn": "Employee",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Preferred Name",
            "dataType": "string",
            "sourceColumn": "Preferred Name",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Is Salesperson",
            "dataType": "boolean",
            "sourceColumn": "Is Salesperson",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "Boolean"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Employee",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Employee].* FROM [Dimension].[Employee] ",
              "dataSource": "SqlServer DESKTOP-M17BHFKMSSQLSERVER19 WideWorldImportersDW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Employee].* FROM [Dimension].[Employee] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Employee"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Stock Item",
        "columns": [
          {
            "name": "Stock Item Key",
            "dataType": "int64",
            "sourceColumn": "Stock Item Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "WWI Stock Item ID",
            "dataType": "int64",
            "sourceColumn": "WWI Stock Item ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Stock Item",
            "dataType": "string",
            "sourceColumn": "Stock Item",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Selling Package",
            "dataType": "string",
            "sourceColumn": "Selling Package",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Buying Package",
            "dataType": "string",
            "sourceColumn": "Buying Package",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Lead Time Days",
            "dataType": "int64",
            "sourceColumn": "Lead Time Days",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Quantity Per Outer",
            "dataType": "int64",
            "sourceColumn": "Quantity Per Outer",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Is Chiller Stock",
            "dataType": "boolean",
            "sourceColumn": "Is Chiller Stock",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "Boolean"
          },
          {
            "name": "Barcode",
            "dataType": "string",
            "sourceColumn": "Barcode",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Tax Rate",
            "dataType": "double",
            "sourceColumn": "Tax Rate",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "sourceColumn": "Unit Price",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Recommended Retail Price",
            "dataType": "double",
            "sourceColumn": "Recommended Retail Price",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Typical Weight Per Unit",
            "dataType": "double",
            "sourceColumn": "Typical Weight Per Unit",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Valid From",
            "dataType": "dateTime",
            "sourceColumn": "Valid From",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Valid To",
            "dataType": "dateTime",
            "sourceColumn": "Valid To",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "Lineage Key",
            "dataType": "int64",
            "sourceColumn": "Lineage Key",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Stock Item",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Dimension].[Stock Item].* FROM [Dimension].[Stock Item] ",
              "dataSource": "SqlServer DESKTOP-M17BHFKMSSQLSERVER19 WideWorldImportersDW"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Dimension].[Stock Item].* FROM [Dimension].[Stock Item] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Stock Item"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Dimension"
          }
        ]
      },
      {
        "name": "Order",
        "columns": [
          {
            "name": "Order Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Key",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "City Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "City Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Customer Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Stock Item Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Stock Item Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Order Date Key",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Order Date Key",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          },
          {
            "name": "Picked Date Key",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Picked Date Key",
            "formatString": "General Date",
            "sourceProviderType": "DBDate"
          },
          {
            "name": "Salesperson Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Salesperson Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Picker Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Picker Key",
            "sourceProviderType": "Integer"
          },
          {
            "name": "WWI Order ID",
            "dataType": "int64",
            "sourceColumn": "WWI Order ID",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Package",
            "dataType": "string",
            "sourceColumn": "Package",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "sourceProviderType": "Integer"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "sourceColumn": "Unit Price",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Tax Rate",
            "dataType": "double",
            "sourceColumn": "Tax Rate",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Total Excluding Tax",
            "dataType": "double",
            "sourceColumn": "Total Excluding Tax",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Tax Amount",
            "dataType": "double",
            "sourceColumn": "Tax Amount",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Total Including Tax",
            "dataType": "double",
            "sourceColumn": "Total Including Tax",
            "sourceProviderType": "Numeric"
          },
          {
            "type": "calculated",
            "name": "Stock Item Name",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('Stock Item'[Stock Item])"
          },
          {
            "type": "calculated",
            "name": "Name of Salesperson",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LOOKUPVALUE(Employee[Employee], [Employee Key], [Salesperson Key])"
          }
        ],
        "partitions": [
          {
            "name": "Order",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": " SELECT [Fact].[Order].* FROM [Fact].[Order] ",
              "dataSource": "SqlServer DESKTOP-M17BHFKMSSQLSERVER19 WideWorldImportersDW"
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of Quantity",
            "expression": "SUM([Quantity])",
            "formatString": "#,0",
            "kpi": {
              "targetExpression": "'Order'[Sum of Quantity Last Year]",
              "targetFormatString": "#,0",
              "statusGraphic": "Road Signs",
              "statusExpression": [
                "var x='Order'[Sum of Quantity]/'Order'[_Sum of Quantity Goal] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.755,-1,",
                "\t                If(x<0.97,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "75.5"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "97"
                }
              ]
            }
          },
          {
            "name": "Total Orders in Dollars",
            "expression": "SUM([Total Excluding Tax])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "kpi": {
              "targetExpression": "200000000",
              "targetFormatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Order'[Total Orders in Dollars] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<102000000,-1,",
                "\t                If(x<189000000,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "102000000"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "189000000"
                }
              ]
            },
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sum of Quantity YTD",
            "expression": "CALCULATE( [Sum of Quantity], DATESYTD('Time'[Date]))",
            "formatString": "#,0"
          },
          {
            "name": "Sum of Quantity Last Year",
            "expression": "CALCULATE([Sum of Quantity], SAMEPERIODLASTYEAR('Time'[Date]))",
            "formatString": "#,0"
          },
          {
            "name": "Order Count",
            "expression": "COUNT('Order'[Order Key])",
            "formatString": "#,0",
            "kpi": {
              "targetExpression": "'Order'[Order Count LY]",
              "targetFormatString": "#,0",
              "statusGraphic": "Traffic Light - Single",
              "statusExpression": [
                "var x='Order'[Order Count]/'Order'[_Order Count Goal] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.886,-1,",
                "\t                If(x<0.965,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "88.6"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "96.5"
                }
              ]
            }
          },
          {
            "name": "Order Count YTD",
            "expression": "CALCULATE( [Order Count], DATESYTD('Time'[Date]))",
            "formatString": "#,0"
          },
          {
            "name": "Order Count LY",
            "expression": "CALCULATE([Order Count], SAMEPERIODLASTYEAR('Time'[Date]))",
            "formatString": "#,0"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [Fact].[Order].* FROM [Fact].[Order] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "Order"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "Fact"
          }
        ]
      },
      {
        "name": "Time",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "[Date]"
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])"
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM,YYYY\")",
            "sortByColumn": "Month Sort"
          },
          {
            "type": "calculated",
            "name": "Month Sort",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date],\"YYYYMM\")"
          },
          {
            "type": "calculated",
            "name": "Day of Month",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "DAY([Date])"
          },
          {
            "type": "calculated",
            "name": "Month of Year",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "Month of Year Sort"
          },
          {
            "type": "calculated",
            "name": "Month of Year Sort",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "MONTH([Date])"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALENDAR(DATE(2013, 1, 1) , DATE(2016, 12, 31) )"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "8aaaa588-9664-4af4-9568-99a67503d1bf",
        "fromTable": "Order",
        "fromColumn": "Picker Key",
        "toTable": "Employee",
        "toColumn": "Employee Key",
        "isActive": false
      },
      {
        "name": "40f76e34-9c09-4dd4-bee1-d21553df484f",
        "fromTable": "Order",
        "fromColumn": "City Key",
        "toTable": "City",
        "toColumn": "City Key"
      },
      {
        "name": "73620682-69bf-4cdf-904c-6c899ba57492",
        "fromTable": "Order",
        "fromColumn": "Customer Key",
        "toTable": "Customer",
        "toColumn": "Customer Key"
      },
      {
        "name": "0f3484bd-e97a-43e2-b59b-de152f4e5ea4",
        "fromTable": "Order",
        "fromColumn": "Salesperson Key",
        "toTable": "Employee",
        "toColumn": "Employee Key"
      },
      {
        "name": "90f6a3a6-2b04-453c-9f2c-c824e34d86b3",
        "fromTable": "Order",
        "fromColumn": "Stock Item Key",
        "toTable": "Stock Item",
        "toColumn": "Stock Item Key"
      },
      {
        "name": "5a03b0d1-0ad3-41ce-91d2-e81402b0d75f",
        "fromTable": "Order",
        "fromColumn": "Order Date Key",
        "toTable": "Time",
        "toColumn": "Date"
      },
      {
        "name": "7cc036a3-0069-48cc-83ad-102275c3223f",
        "fromTable": "Order",
        "fromColumn": "Picked Date Key",
        "toTable": "Time",
        "toColumn": "Date",
        "isActive": false
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "400"
      }
    ]
  },
  "id": "SemanticModel"
}